# Generated by Django 5.1.5 on 2025-03-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_feename_amount_remove_feename_description_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippayment',
            name='user',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='currency',
            field=models.CharField(default='BDT', max_length=5),
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='payment_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='membership_payments', to='accounts.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='refund_status',
            field=models.CharField(choices=[('NOT_REFUNDED', 'Not Refunded'), ('REFUNDED', 'Refunded')], default='NOT_REFUNDED', max_length=20),
        ),
        migrations.AddField(
            model_name='mobilebankingdetail',
            name='currency',
            field=models.CharField(default='BDT', max_length=5),
        ),
        migrations.AddField(
            model_name='mobilebankingdetail',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
