# Generated by Django 5.1.5 on 2025-03-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_feename_amount_remove_feename_description_and_more'),
        ('payment', '0002_remove_membershippayment_user_bankdetail_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='fee_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.feestructure'),
            preserve_default=False,
        ),
    ]
