# Generated by Django 5.1.5 on 2025-03-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_membershippayment_fee_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_method',
            field=models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking')], default='BANK_TRANSFER', max_length=20),
        ),
    ]
