# Generated by Django 5.1.5 on 2025-03-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_membershippayment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershippayment',
            name='payment_month',
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='payment_months',
            field=models.TextField(blank=True, null=True),
        ),
    ]
