# Generated by Django 5.1.5 on 2025-03-27 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_membershippayment_payment_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
