# Generated by Django 5.1.5 on 2025-03-27 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_membershippayment_payment_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankingInformation',
        ),
        migrations.DeleteModel(
            name='MobileBanking',
        ),
        migrations.DeleteModel(
            name='RegistrationPayment',
        ),
    ]
