# Generated by Django 5.1.5 on 2025-03-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_delete_bankinginformation_delete_mobilebanking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bankdetail'),
        ),
    ]
