# Generated by Django 5.1.5 on 2025-03-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_membershippayment_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankdetail',
            old_name='currency',
            new_name='currencey',
        ),
        migrations.RemoveField(
            model_name='membershippayment',
            name='bank',
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.bankdetail'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='mobile_banking_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.mobilebankingdetail'),
        ),
    ]
