# Generated by Django 5.1.5 on 2025-04-13 10:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_committeemember_designation'),
        ('payment', '0009_rename_currency_bankdetail_currencey_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_member', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking')], default='BANK_TRANSFER', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='donation_proofs/')),
                ('donattion_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='club.committee')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
