# Generated by Django 5.1.5 on 2025-04-13 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_committeedonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeedonation',
            name='bank_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bankdetail'),
        ),
        migrations.AddField(
            model_name='committeedonation',
            name='mobile_banking_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.mobilebankingdetail'),
        ),
    ]
