# Generated by Django 5.1.5 on 2025-04-13 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_rename_name_committeedonation_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeedonation',
            old_name='full_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='committeedonation',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
