# Generated by Django 5.1.5 on 2025-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_donationtype_committeedonation_donation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeedonation',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For non-cash donations like rice or blood (bags/kg/etc.)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='committeedonation',
            name='quantity_unit',
            field=models.CharField(blank=True, help_text='Unit for quantity, like kg, bags, liters', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='committeedonation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For monetary donations', max_digits=10, null=True),
        ),
    ]
