# Generated by Django 5.1.5 on 2025-04-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0016_committeedonation_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeedonation',
            name='payment_method',
            field=models.CharField(choices=[('----', 'Select Payment Method'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking')], default='----', max_length=20),
        ),
        migrations.AlterField(
            model_name='membershippayment',
            name='payment_method',
            field=models.CharField(choices=[('----', 'Select Payment Method'), ('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking')], default='----', max_length=20),
        ),
    ]
