# Generated by Django 5.1.5 on 2025-04-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_committeedonation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationtype',
            name='amount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='bank_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='mobile_banking_detail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='payment_method',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='proof_of_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='quantity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='quantity_unit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationtype',
            name='transaction_id',
            field=models.BooleanField(default=False),
        ),
    ]
