# Generated by Django 5.1.5 on 2025-04-19 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_donationtype_amount_donationtype_bank_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donationtype',
            options={},
        ),
        migrations.AlterField(
            model_name='committeedonation',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, null=True),
        ),
    ]
