# Generated by Django 5.1.5 on 2025-04-20 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_alter_donationtype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='committeedonation',
            name='quantity_unit',
            field=models.ForeignKey(blank=True, help_text='Unit of measurement for quantity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.donationunit'),
        ),
    ]
