# Generated by Django 5.1.5 on 2025-03-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_feestructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='description',
        ),
    ]
