# Generated by Django 5.1.5 on 2025-03-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_feestructure_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('is_one_time', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='is_one_time',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='name',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='fee_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.feename'),
        ),
    ]
