# Generated by Django 5.1.5 on 2025-03-24 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_feename_remove_feestructure_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feename',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.membershiptype'),
        ),
    ]
