# Generated by Django 5.1.5 on 2025-03-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_membershiptype_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feename',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feename',
            name='description',
        ),
        migrations.RemoveField(
            model_name='feename',
            name='is_one_time',
        ),
        migrations.RemoveField(
            model_name='feename',
            name='membership',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='is_one_time',
            field=models.BooleanField(default=False),
        ),
    ]
