# Generated by Django 5.1.5 on 2025-03-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_feename_amount_remove_feename_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
