# Generated by Django 5.1.5 on 2025-04-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_feestructure_created_at_feestructure_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='updated_by',
        ),
    ]
