# Generated by Django 5.1.5 on 2025-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_feestructure_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Select', 'Select'), ('Admin', 'Administrator'), ('Member', 'Member'), ('Volunteer', 'Volunteer')], default='Member', max_length=20),
        ),
    ]
