# Generated by Django 5.1.5 on 2025-04-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_committeemember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommitteeMember',
        ),
    ]
