# Generated by Django 5.1.5 on 2025-04-13 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_feestructure_counter'),
        ('club', '0003_delete_committeemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='club.committee')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.committeedesignation')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
