# Generated by Django 5.1.5 on 2025-04-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_committeemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
