# Generated by Django 5.1.5 on 2025-04-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_committeemember_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='committeeregistration',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='committeeregistration',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='committeeregistration',
            name='member',
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.designation'),
        ),
        migrations.DeleteModel(
            name='CommitteeDesignation',
        ),
        migrations.DeleteModel(
            name='CommitteeRegistration',
        ),
    ]
