# Generated by Django 5.1.5 on 2025-04-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_designation_remove_committeeregistration_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='task',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
