# Generated by Django 5.1.5 on 2025-04-13 17:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_committeemember_task'),
        ('payment', '0014_alter_committeedonation_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(default=datetime.date.today)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking')], default='bank_transfer', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('proof_of_payment', models.ImageField(blank=True, null=True, upload_to='expense_proofs/')),
                ('expense_notes', models.TextField(blank=True, null=True)),
                ('bank_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.bankdetail')),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='club.committee')),
                ('mobile_banking_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.mobilebankingdetail')),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_expenses', to='club.expensetype')),
            ],
        ),
    ]
