# Generated by Django 5.1.5 on 2025-04-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_expensetype_committeeexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeexpense',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committeeexpense',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
