# Generated by Django 5.1.5 on 2025-04-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_committeeexpense_description_committeeexpense_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeexpense',
            name='members',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='club.committeemember'),
            preserve_default=False,
        ),
    ]
