# Generated by Django 5.1.5 on 2025-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeemember',
            name='task',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='activities',
            field=models.ManyToManyField(blank=True, to='club.activity'),
        ),
    ]
