# Generated by Django 5.1.5 on 2025-04-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_remove_committeemember_task_and_more'),
        ('payment', '0019_alter_donationtype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeexpense',
            name='donation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='committee_expenses', to='payment.donationtype'),
        ),
    ]
