# Generated by Django 5.1.5 on 2025-04-21 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_committeeexpense_donation_type'),
        ('payment', '0020_donationunit_alter_committeedonation_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeexpense',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='committeeexpense',
            name='quantity_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.donationunit'),
        ),
    ]
