# Generated by Django 5.1.5 on 2025-04-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_committeeexpense_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeexpense',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
