# Generated by Django 5.1.5 on 2025-04-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_alter_committeeexpense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeexpense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Bank Transfer'), ('mobile_banking', 'Mobile Banking')], default='bank_transfer', max_length=20, null=True),
        ),
    ]
