# Generated by Django 5.1.5 on 2025-04-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0017_committeeexpense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeexpense',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
