# Generated by Django 5.1.5 on 2025-04-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0018_committeeexpense_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeexpense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
