# Generated by Django 5.1.5 on 2025-05-07 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0019_alter_committeeexpense_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_expense', models.BooleanField(default=False)),
                ('can_approve_expense', models.BooleanField(default=False)),
                ('can_view_expense', models.BooleanField(default=False)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='club.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='club.committeemember')),
            ],
        ),
    ]
