# Generated by Django 5.1.5 on 2025-05-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_committeepermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeepermission',
            old_name='can_create_expense',
            new_name='can_approve_donation',
        ),
        migrations.RenameField(
            model_name='committeepermission',
            old_name='can_view_expense',
            new_name='can_reject_donation',
        ),
        migrations.AddField(
            model_name='committeepermission',
            name='can_reject_expense',
            field=models.BooleanField(default=False),
        ),
    ]
